packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  puppeteer: true
  unrs-resolver: true
