import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

// AES-256-GCM encryption for Authentication Configuration secrets
// (REQ-SEC-002 §14: "Secret Credential Value không được hiển thị lại dưới
// dạng plaintext"). Key is app-level configuration (CREDENTIAL_ENCRYPTION_KEY
// env var, base64-encoded 32 bytes), read directly from process.env per this
// codebase's established convention (no ConfigService injection anywhere) —
// same lazy-read-at-call-time pattern as sessions.service.ts's
// SESSION_TTL_HOURS. The key never enters the database.

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH_BYTES = 12;
const KEY_LENGTH_BYTES = 32;

// Plain Uint8Array (not Buffer) so these assign directly into Prisma's
// generated Bytes field type (Uint8Array<ArrayBuffer> in Prisma 7) without a
// structural mismatch against Buffer's wider ArrayBufferLike parameter.
export interface EncryptedSecret {
  ciphertext: Uint8Array<ArrayBuffer>;
  iv: Uint8Array<ArrayBuffer>;
  authTag: Uint8Array<ArrayBuffer>;
}

function loadEncryptionKey(): Buffer {
  const raw = process.env.CREDENTIAL_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error("CREDENTIAL_ENCRYPTION_KEY is not configured");
  }
  const key = Buffer.from(raw, "base64");
  if (key.length !== KEY_LENGTH_BYTES) {
    throw new Error("CREDENTIAL_ENCRYPTION_KEY must be a base64-encoded 32-byte (AES-256) key");
  }
  return key;
}

function toBytes(buffer: Buffer): Uint8Array<ArrayBuffer> {
  return new Uint8Array(buffer);
}

export function encryptSecret(plaintext: string): EncryptedSecret {
  const key = loadEncryptionKey();
  const iv = randomBytes(IV_LENGTH_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return { ciphertext: toBytes(ciphertext), iv: toBytes(iv), authTag: toBytes(authTag) };
}

export function decryptSecret(secret: EncryptedSecret): string {
  const key = loadEncryptionKey();
  const decipher = createDecipheriv(ALGORITHM, key, secret.iv);
  decipher.setAuthTag(secret.authTag);
  const plaintext = Buffer.concat([decipher.update(secret.ciphertext), decipher.final()]);
  return plaintext.toString("utf8");
}
